Code = "en_US"


[Strings]
#Commands
command_avatar_desc = "Fetch a user's avatar"
command_avatar_usage = "y!avatar | y!avatar @exampleuser#1234"

command_ping_desc = "Pong! Find out the bot's latency"
command_ping_usage = "y!ping"

command_repeat_desc = "I repeat the next message you say!"
command_repeat_usage = "y!repeat text"

command_cry_desc = "Send a crying gif/image"
command_cry_usage = "y!cry"

command_cuddle_desc = "Cuddle someone!"
command_cuddle_usage = "y!cuddle"

command_hug_desc = "Give or get a hug!"
command_hug_usage = "y!hug"

command_kiss_desc = "Give someone a kiss!"
command_kiss_usage = "y!repeat"

command_lewd_desc = "I-Is someone being lewd...?"
command_lewd_usage = "y!lewd"

command_lick_desc = "L-Lick someone?"
command_lick_usage = "y!lick"

command_nom_desc = "Bite someone"
command_nom_usage = "y!nom"

command_nyan_desc = "Neko!"
command_nyan_usage = "y!nyan"

command_owo_desc = "OwO"
command_owo_usage = "y!owo"

command_pat_desc = "Give or get a pat"
command_pat_usage = "y!pat"

command_pout_desc = "Pout"
command_pout_usage = "y!pout"

command_rem_desc = "Send an image of rem"
command_rem_usage = "y!rem"

command_slap_desc = "Give a slap"
command_slap_usage = "y!slap"

command_smug_desc = "Be smug"
command_smug_usage = "y!smug"

command_stare_desc = "Stare at someone"
command_stare_usage = "y!stare"

command_tickle_desc = "T-Tickle someone!"
command_tickle_usage = "y!tickle"

command_vote_desc = "Vote for a poll"
command_vote_usage = "y!vote pollid\ny!vote pollid option"

command_createpoll_desc = "Create a new poll for your users to vote in!"
command_createpoll_usage = "y!createpoll\ny!createpoll title"

command_serverinfo_desc = "Get information on a server"
command_serverinfo_usage = "y!serverinfo"

command_8ball_desc = "Shake an 8ball!"
command_8ball_usage = "y!8ball\ny!8ball Will I ever get doughnuts?"

command_config_desc = "Modify settings in your server"
command_config_usage = "y!config"

command_roulette_desc = "Pull the trigger in russian roulette"
command_roulette_usage = "y!roulette"

command_roulette_join_desc = "Join or start a game of Russian Roulette"
command_roulette_join_usage = "y!roulette join"

command_roulette_start_desc = "Start a game of russian roulette"
command_roulette_start_usage = "y!roulette start"

command_roulette_kick_desc = "Kick a player from a game of russuan roulette"
command_roulette_kick_usage = "y!roulette kick @JoeCool777#1337"

command_roulette_quit_desc = "Leave a game of russian roulette"
command_roulette_quit_usage = "y!roulette quit"

command_roulette_players_desc = "View current players"
command_roulette_players_usage = "y!roulette players"

command_toss_desc = "Toss a coin"
command_toss_usage = "y!toss"

command_roll_desc = "Roll the dice!"
command_roll_usage = "y!roll"

command_rolecol_desc = "Change a role's color"
command_rolecol_usage = "y!rolecol role name hexcode"

command_userinfo_desc = "Get information on a user"
command_userinfo_usage = "y!userinfo\ny!userinfo @I_AM_AWESOME@6969"

command_ban_desc = "Ban someone"
command_ban_usage = "y!ban @genericuser#1234"

command_kick_desc = "Kick someone from your server"
command_kick_usage = "y!kick @genericuser2#3456"

command_calculate_desc = "Perform simple calculations"
command_calculate_usage = "y!calculate 2+2"

command_choose_desc = "Pick between a set of options"
command_choose_usage = "y!choose apple | banana"

command_roleinfo_desc = "Get information on a role"
command_roleinfo_usage = "y!roleinfo Admin"

command_viewpoll_desc = "View a poll"
command_viewpoll_usage = "y!viewpoll pollid"

command_modules_desc = "View a list of modules"
command_modules_usage = "y!modules"

command_help_desc = "Learn a bit about how to use the bot, or get help on a command"
command_help_usage = "y!help\ny!help commandName"

command_boobs_desc = "Get a random boobs image"
command_boobs_usage = "y!boobs"

command_butts_desc = "Get a random butts image"
command_butts_usage = "y!butts"

command_hentai_desc = "Search for hentai"
command_hentai_usage = "y!hentai\ny!hentai terms"

command_rule34_desc = "Search rule34.xxx"
command_rule34_usage = "y!rule34\ny!rule34 terms"

command_e621_desc = "Search e621"
command_e621_usage = "y!e621\ny!e621 terms"

command_booru_desc = "Search gelbooru and danbooru for an SFW image"
command_booru_usage = "y!booru\ny!booru terms"

command_gelbooru_desc = "Search gelbooru for an SFW image"
command_gelbooru_usage = "y!gelbooru\ny!gelbooru terms"

command_danbooru_desc = "Search danbooru for an SFW image"
command_danbooru_usage = "y!danbooru\ny!danbooru terms"



#Strings
require_permission_manage_roles = "Sorry! I need the permission Manage Roles to run this command."

only_dm_channel = "This command can only be executed in a DM channel."
success = "Success!"
none = "None"
activity= "Activity"

_true = "Yes"
_false = "No"

invisible = "Invisible"
offline = "Offline"
away = "Away"
donotdisturb = "Do Not Disturb"

listening = "Listening To"
playing = "Playing"
streaming = "Streaming"
watching = "Watching"

error_occurred = "An error occurred! Contact my owner ASAP so this can get fixed"
incorrect_response_string = "Incorrect response string!"

ping_pinging = "Pinging..."
ping_pong = "Pong!"
ping_latency = "Took %latency%ms to respond."
ping_api_latency = "API latency: %latency%ms"

avatar_user_avatar = "%username_full%'s avatar"

interactive_repeat_send_message = "Send a message!"

rammoe_cry = "Aww, %executor% is crying! There, there."
rammoe_cuddle = "%user%, you got a cuddle from %executor%! How cute!"
rammoe_cuddle_alt = "%executor%, you got a cuddle from %user%"
rammoe_hug = "%user%, you got a hug from %executor%!"
rammoe_hug_alt = "%executor%, you got a hug from %user%!"
rammoe_kiss = "%user%, you got a kiss from %executor%!"
rammoe_kiss_alt = "%executor%, you got a kiss from %user%!"
rammoe_lewd = "%executor% thinks %user% is being lewd!"
rammoe_lewd_alt = "%executor% is being lewd!"
rammoe_lick = "%executor% licked %user%!"
rammoe_lick_alt = "%executor% is licking themself!"
rammoe_nom = "%executor% nommed %user%!"
rammoe_nom_alt = "%executor% got nommed by %user%"
rammoe_nyan = "nyan"
rammoe_owo = "owo"
rammoe_pat = "%user% got a pat from %executor%!"
rammoe_pat_alt = "%executor% got patted by %user%!"
rammoe_pout = "%executor% is pouting!"
rammoe_rem = "rem"
rammoe_slap = "%executor% slapped %user%!"
rammoe_slap_alt = "%executor% got slapped by %user%!"
rammoe_smug = "%executor% is being smug to %user%"
rammoe_smug_alt = "%executor% is being smug!"
rammoe_stare = "%executor% is staring at %user% :eyes:"
rammoe_stare_alt = "%executor% is staring :eyes:"
rammoe_tickle = "%user% got tickled by %executor%!"
rammoe_tickle_alt = "%executor% got tickled by %user%!"
rammoe_nsfw_gtn = "nsfw"

poll_not_found = "I couldn't find a poll with ID %id%!"
poll_not_in_server = "Sorry! You can't vote for this poll because you're not in the server this poll was created in."
poll_ended = "This poll has ended."
poll_vote = "Please vote (item number or name) :"
poll_unknown_item = "Poll item unknown!"
poll_already_voted = "You've already voted for this poll! If you'd like to recase your vote, type \"yes\" and rerun this command."
poll_response_recorded = "Your response has been recorded. Thank you for participating! To vote again, rerun the command with the poll ID."

poll_create_creating = "Creating new poll..."
poll_create_created = "Poll created!"
poll_creating_title_str = "Title"
poll_creating_items_str = "Items"
poll_create_items_desc = "Items are separated by | and require at LEAST two choices. Example: option 1 | option 2 | option 3"
poll_creating_deadline_str = "Deadline"
poll_create_deadline_desc = "When the poll ends. Example: 2d 1h 3m (deadline will be 2 days, 1 hour, 3 minutes from now)"
poll_create_show_vote_str = "Show votes"
poll_create_show_vote_desc = "Should vote count on choices be shown to everyone? Answer y for yes, and n for no"
poll_create_title = "What's the title of this poll?"
poll_create_title_long = "Title too long! Has to be less than 300 characters."
poll_create_items = "What are the items to choose from?"
poll_create_items_short = "Too few choices! Must have at least two."
poll_create_deadline = "When will this poll end?"
poll_create_deadline_invalid = "Not a valid Date!"
poll_create_deadline_long = "Date too long! Must be less than two weeks from now."
poll_create_allow_view = "Should vote count on choices be shown to everyone?"
poll_created_id = "Poll ID"

serverinfo_owner = "Owner"
serverinfo_verification_level = "Verification Level"
serverinfo_region = "Region"
serverinfo_categories = "Categories"
serverinfo_channels = "Channels"
serverinfo_channels_text = "Text Channels"
serverinfo_channels_voice = "Voice Channels"
serverinfo_members = "Members"
serverinfo_online = "online"
serverinfo_roles = "Roles"
serverinfo_roles_view = "To view a list of roles, run y!serverroles"
serverinfo_created = "Created"

eightball_response_title = "Magic 8Ball says"
eightball_response_1 = "It is certain."
eightball_response_2 = "It is decidedly so."
eightball_response_3 = "Without a doubt."
eightball_response_4 = "Yes - definitely."
eightball_response_5 = "You may rely on it."
eightball_response_6 = "As I see it, yes."
eightball_response_7 = "Most likely."
eightball_response_8 = "Outlook good."
eightball_response_9 = "Yes."
eightball_response_10 = "Signs point to yes."
eightball_response_11 = "Reply hazy, try again."
eightball_response_12 = "Ask again later."
eightball_response_13 = "Better not tell you now."
eightball_response_14 = "Cannot predict now."
eightball_response_15 = "Concentrate and ask again."
eightball_response_16 = "Don't count on it."
eightball_response_17 = "My reply is no."
eightball_response_18 = "My sources say no."
eightball_response_19 = "Outlook not so good."
eightball_response_20 = "Very doubtful."

config_title = "Configuration"
config_setting_join_leave = "Modify Greeting/Goodbye message"
config_setting_commands = "Modify command settings"
config_setting_data= "Modify server message cache settings"
config_setting_warnings = "Modify settings for warnings"

rolecol_bot_require_higher = "I can't modify this role! It's higher than my highest :("
rolecol_user_require_higher = "I can't modify this role! It's higher than your highest :("
rolecol_set = "Successfully changed the color of `%rolename%` from %oldcol% to %newcol%"

roulette_killed = "Sorry, %user%! You were shot!"
roulette_safe = "%user%, you're safe!"
roulette_not_current_player = "Sorry, %user%, you're not the current player!"
roulette_not_started = "This game hasn't started yet! To start it, run \"y!roulette start\""
roulette_no_game = "No game has been created! To create one, run \"y!roulette join\""
roulette_game_over = "Sorry, %user%, you were shot! Game Over!"
roulette_error = "Oops, an error occurred! Please contact my owner as soon as you can!"
roulette_playing = "The game has began!"
roulette_not_enough_players = "There are not enough players to start this game"
roulette_not_game_master = "I'm sorry, but you can't do that! You must be the game master."
roulette_next_player = "%nuser%, there are %bullets% chambers left."
roulette_winner = "%nuser%, you win!"
roulette_trigger_pulled = "%user% pulls the trigger..."
roulette_join_success = "Successfully joined the game! **%spotsleft%** more players can join this game."
roulette_join_fail = "You can't join this game!"
roulette_quit = "%user% left the game"
roulette_player_kicked = "%user%, you were kicked from the game"
roulette_starting = "The game is starting"

coin_heads = "heads"
coin_tails = "tails"
coin_flipped = "%user%, you flipped a coin!"

roll_rolled = "You rolled a %dice%!"

uinf_id = "Id"
uinf_status = "Status"
uinf_acc_create = "Account Created"
uinf_acc_join = "Join Date"
uinf_permissions = "Guild Permissions"
uinf_roles = "Roles [%count%]"

roleinfo_id = "ID"
roleinfo_position = "Position"
roleinfo_created = "Role Created"
roleinfo_hoisted = "Listed Separately"
roleinfo_mentionable = "Mentionable"
roleinfo_managed = "Managed by Discord"
roleinfo_permissions = "Permissions"


modules_title = "List of Modules"
modules_help = "To view commands in a module, use the command y!commands moduleName"
modules_count = "%cmds% command(s)"

commands_title = "List of Commands"
commands_help = "To view information on a command, use the command y!help commandName"
commands_no_alias = "No aliases"

help_title = "Looking for help?"
help_aliases = "Aliases"
help_usage = "Usage"
help_info_description = "To add me to your own server, [click here!](https://discordapp.com/oauth2/authorize?client_id=338887651677700098&scope=bot&permissions=271690950)\n\n\n• For a list of modules, use `y!modules`\n• To view commands in a module, use `y!commands moduleName`\n\nInterested in supporting my development and getting some perks? Use `y!donate`!\n\nNeed to report a bug or want to request a feature? Join my [support server!](https://discord.gg/qA4c4f3)"
help_description = "Description"

remindme_success = ":thumbsup: Got it, %user%! I'll remember to remind you about this:\n\n%reminder%"
remindme_datetime_short = "Sorry! The time must be greater than or equal to 1 minute."