Playing = [
	"Minecraft", "with %usercount% users",
	"in %guildcount% guilds", "Shard %shardid% (%usercount% users)",
	"y!donate to support me",
	"Fortnite", "Overwatch", "y!scramblr", "y!help"
]

Listening = [
	"Bad Guy", "Despacito"
]

Watching = [
	"you", "RTGame",
	"CallMeKevin", "YouTube"
]