Playing = [
	"Minecraft", "with %usercount% users",
	"in %guildcount% guilds",
	"Shard %shardid% (%usercount% users)",
	"y!donate to support me",
	"Now with Patron features!",
	"Updated server invite!",
	"Need help? y!help"
	"Fortnite", "Overwatch",
	"y!scramblr"
]

Listening = [
	"music"
]

Watching = [
	"you", "YouTube"
]