Code = "en_US"


#Commands
[[Command]]
Name = "avatar"
Summary = "Fetch a user's avatar"
Usage = "y!avatar | y!avatar @exampleuser#1234"

[[Command]]
Name = "ping"
Summary = "Pong! Find out the bot's latency"
Usage = "y!ping"

[[Command]]
Name = "repeat"
Summary = "I repeat the next message you say!"
Usage = "y!repeat"

[[Command]]
Name = "cry"
Summary = "Send a crying gif/image"
Usage = "y!cry"

[[Command]]
Name = "cuddle"
Summary = "Cuddle someone!"
Usage = "y!cuddle"

[[Command]]
Name = "hug"
Summary = "Give or get a hug!"
Usage = "y!hug"

[[Command]]
Name = "kiss"
Summary = "Give someone a kiss!"
Usage = "y!repeat"

[[Command]]
Name = "lewd"
Summary = "I-Is someone being lewd...?"
Usage = "y!lewd"

[[Command]]
Name = "lick"
Summary = "L-Lick someone?"
Usage = "y!lick"

[[Command]]
Name = "nom"
Summary = "Bite someone"
Usage = "y!nom"

[[Command]]
Name = "nyan"
Summary = "Neko!"
Usage = "y!nyan"

[[Command]]
Name = "owo"
Summary = "OwO"
Usage = "y!owo"

[[Command]]
Name = "pat"
Summary = "Give or get a pat"
Usage = "y!pat"

[[Command]]
Name = "pout"
Summary = "Pout"
Usage = "y!pout"

[[Command]]
Name = "rem"
Summary = "Send an image of rem"
Usage = "y!rem"

[[Command]]
Name = "slap"
Summary = "Give a slap"
Usage = "y!slap"

[[Command]]
Name = "smug"
Summary = "Be smug"
Usage = "y!smug"

[[Command]]
Name = "stare"
Summary = "Stare at someone"
Usage = "y!stare"

[[Command]]
Name = "tickle"
Summary = "T-Tickle someone!"
Usage = "y!tickle"


#Strings
[Strings]
only_dm_channel = "This command can only be executed in a DM channel."

ping_pinging = "Pinging..."
ping_pong = "Pong!"
ping_latency = "Took %latency%ms to respond."
ping_api_latency = "API latency: %latency%ms"

avatar_user_avatar = "%username_full%'s avatar"

interactive_repeat_send_message = "Send a message!"

rammoe_cry = "Aww, %executor% is crying! There, there."
rammoe_cuddle = "%user%, you got a cuddle from %executor%! How cute!"
rammoe_cuddle_alt = "%executor%, you got a cuddle from %user%"
rammoe_hug = "%user%, you got a hug from %executor%!"
rammoe_hug_alt = "%executor%, you got a hug from %user%!"
rammoe_kiss = "%user%, you got a kiss from %executor%!"
rammoe_kiss_alt = "%executor%, you got a kiss from %user%!"
rammoe_lewd = "%executor% thinks %user% is being lewd!"
rammoe_lewd_alt = "%executor% is being lewd!"
rammoe_lick = "%executor% licked %user%!"
rammoe_lick_alt = "%executor% is licking themself!"
rammoe_nom = "%executor% nommed %user%!"
rammoe_nom_alt = "%executor% got nommed by %user%"
rammoe_nyan = "nyan"
rammoe_owo = "owo"
rammoe_pat = "%user% got a pat from %executor%!"
rammoe_pat_alt = "%executor% got patted by %user%!"
rammoe_pout = "%executor% is pouting!"
rammoe_rem = "rem"
rammoe_slap = "%executor% slapped %user%!"
rammoe_slap_alt = "%executor% got slapped by %user%!"
rammoe_smug = "%executor% is being smug to %user%"
rammoe_smug_alt = "%executor% is being smug!"
rammoe_stare = "%executor% is staring at %user% :eyes:"
rammoe_stare_alt = "%executor% is staring :eyes:"
rammoe_tickle = "%user% got tickled by %executor%!"
rammoe_tickle_alt = "%executor% got tickled by %user%!"
rammoe_nsfw_gtn = "nsfw"

poll_not_found = "I couldn't find a poll with ID %id%!"
poll_not_in_server = "Sorry! You can't vote for this poll because you're not in the server this poll was created in."
poll_ended = "This poll has ended."
poll_vote = "Please vote (item number or name) :"
poll_unknown_item = "Poll item unknown!"
poll_already_voted = "You've already voted for this poll! If you'd like to recase your vote, type \"yes\" and rerun this command."
poll_response_recorded = "Your response has been recorded. Thank you for participating! To vote again, rerun the command with the poll ID."

poll_create_creating = "Creating new poll..."
poll_create_created = "Poll created!"
poll_creating_title_str = "Title"
poll_creating_items_str = "Items"
poll_create_items_desc = "Items are separated by | and require at LEAST two choices. Example: option 1 | option 2 | option 3"
poll_creating_deadline_str = "Deadline"
poll_create_deadline_desc = "When the poll ends. Example: 2d 1h 3m (deadline will be 2 days, 1 hour, 3 minutes from now)"
poll_create_show_vote_str = "Show votes"
poll_create_show_vote_desc = "Should vote count on choices be shown to everyone? Answer y for yes, and n for no"
poll_create_title = "What's the title of this poll?"
poll_create_title_long = "Title too long! Has to be less than 300 characters."
poll_create_items = "What are the items to choose from?"
poll_create_items_short = "Too few choices! Must have at least two."
poll_create_deadline = "When will this poll end?"
poll_create_deadline_invalid = "Not a valid Date!"
poll_create_deadline_long = "Date too long! Must be less than two weeks from now."
poll_create_allow_view = "Should vote count on choices be shown to everyone?"
poll_created_id = "Poll ID"

serverinfo_owner = "Owner"
serverinfo_verification_level = "Verification Level"
serverinfo_region = "Region"
serverinfo_categories = "Categories"
serverinfo_channels = "Channels"
serverinfo_channels_text = "Text Channels"
serverinfo_channels_voice = "Voice Channels"
serverinfo_members = "Members"
serverinfo_online = "online"
serverinfo_roles = "Roles"
serverinfo_roles_view = "To view a list of roles, run y!serverroles"
serverinfo_created = "Created"

eightball_response_title = "Magic 8Ball says"
eightball_response_1 = "It is certain."
eightball_response_2 = "It is decidedly so."
eightball_response_3 = "Without a doubt."
eightball_response_4 = "Yes - definitely."
eightball_response_5 = "You may rely on it."
eightball_response_6 = "As I see it, yes."
eightball_response_7 = "Most likely."
eightball_response_8 = "Outlook good."
eightball_response_9 = "Yes."
eightball_response_10 = "Signs point to yes."
eightball_response_11 = "Reply hazy, try again."
eightball_response_12 = "Ask again later."
eightball_response_13 = "Better not tell you now."
eightball_response_14 = "Cannot predict now."
eightball_response_15 = "Concentrate and ask again."
eightball_response_16 = "Don't count on it."
eightball_response_17 = "My reply is no."
eightball_response_18 = "My sources say no."
eightball_response_19 = "Outlook not so good."
eightball_response_20 = "Very doubtful."