// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yuki.Bot.Misc.Database;

namespace Yuki.Migrations
{
    [DbContext(typeof(YukiContext))]
    [Migration("20190429043337_nsfwChannelMigration")]
    partial class nsfwChannelMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Yuki.Bot.Misc.Database.AutoAssignRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("ApplyTime");

                    b.Property<ulong>("RoleId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("AutoAssignedRoles");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.AutoBanUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ServerId");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.ToTable("AutoBanUsers");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CmdName");

                    b.Property<string>("CmdResponse");

                    b.Property<int>("CmdType");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.CustomPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ServerId");

                    b.Property<string>("prefix");

                    b.HasKey("Id");

                    b.ToTable("CustomPrefixes");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.DataOptIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("UserId");

                    b.Property<bool>("optedIn");

                    b.HasKey("Id");

                    b.ToTable("DataCollectionOptIn");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.GuildWarningAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<ulong>("RoleId");

                    b.Property<ulong>("ServerId");

                    b.Property<int>("Warning");

                    b.HasKey("Id");

                    b.ToTable("WarningActions");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.IgnoredChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("IgnoredChannels");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.IgnoredServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsIgnored");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("IgnoredServers");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.JoinLeaveMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MsgType");

                    b.Property<ulong>("ServerId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("JoinLeaveMessages");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.LogChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("LogChannels");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.MuteRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("RoleId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("MuteRole");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.NsfwChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("NsfwChannels");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.Purgeable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LeaveDate");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("Purgeable");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("RoleId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<ulong>("ServerId");

                    b.Property<bool>("State");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.WarnedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ServerId");

                    b.Property<ulong>("UserId");

                    b.Property<string>("WarnReasons");

                    b.Property<int>("Warning");

                    b.HasKey("Id");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("Yuki.Bot.Misc.Database.WelcomeChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("WelcomeChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
